"""Build the deterministic `nox.pyz` zipapp (C-1038).

Not part of the `nox` package: this is a build tool, it never ships inside the
archive it produces, and it must run on a bare interpreter with no `nox` import.

`zipapp.create_archive` is deliberately not used. It offers no control over
`ZipInfo.date_time`, the compression method or the external attributes, and its
generated `__main__.py` does `from nox.cli import main`, which imports the `nox`
package first — and `nox/__init__.py` re-exports eagerly, so on an interpreter
below the floor that raises `ImportError` before `cli._require_python()` can
produce its one-line remedy. The `__main__.py` emitted here therefore carries
the floor check itself, in syntax valid on 3.8, before it touches the package.
"""

from __future__ import annotations

import argparse
import ast
import hashlib
import io
import os
import time
import zipfile
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["DEFAULT_EPOCH", "MAIN_SOURCE", "SHEBANG", "build", "main"]

SHEBANG: bytes = b"#!/usr/bin/env python3\n"
"""Prepended to the archive bytes. `python3`, never a versioned interpreter."""

DEFAULT_EPOCH: tuple[int, int, int, int, int, int] = (1980, 1, 1, 0, 0, 0)
"""The zip epoch, used when `SOURCE_DATE_EPOCH` is unset. 1980 is the floor a
zip `date_time` can express; anything earlier is unrepresentable."""

_GUARD_MARKER = "__FLOOR_GUARD__"
"""Replaced in `MAIN_SOURCE` by `cli.py`'s `_require_python` source, verbatim.
A marker rather than `str.format`: the lifted segment is arbitrary source and
must not be scanned for braces."""

MAIN_SOURCE: str = '''"""nox.pyz entry point — the Python floor guard, then the CLI (C-1039).

Generated by `nox/scripts/build_pyz.py`; do not edit inside the archive.
`_require_python` below is lifted verbatim out of `nox/src/nox/cli.py`, so the
two can never drift, and it runs before the first `nox` import: `nox/__init__.py`
re-exports eagerly, so on a sub-floor interpreter that import raises the bare
`ImportError` this guard exists to replace. Every line here is syntax valid on
3.8 — the interpreter this must survive is by definition one that cannot parse
the package it guards.
"""

__FLOOR_GUARD__


_require_python()

from nox.cli import main  # noqa: E402

raise SystemExit(main())
'''
"""The `__main__.py` written into the archive, with the guard still to splice in."""

_ALLOWED_SUFFIX = ".py"
_ALLOWED_NAME = "py.typed"


def _refuse_irregular(path: Path) -> None:
    """Refuse anything that is not a plain directory or a regular file.

    `shutil.copytree` and friends default to `symlinks=False`: a symlink under
    the package would be dereferenced and its *target's* bytes packed into a
    published artifact, which is a file-exfiltration primitive. A fifo, socket
    or device is undefined input. Both are refused before anything is written.
    """
    if path.is_symlink() or not (path.is_dir() or path.is_file()):
        raise ValueError(f"{path} is a symlink or not a regular file; refusing to build nox.pyz from this tree")


def _members(source: Path) -> list[str]:
    """Sorted `source`-relative POSIX paths of the files to pack (allowlisted)."""
    _refuse_irregular(source)  # os.walk follows its root argument whatever `followlinks` says
    members: list[str] = []
    for root, directories, files in os.walk(source):
        parent = Path(root)
        for name in sorted(directories):
            _refuse_irregular(parent / name)
        for name in sorted(files):
            path = parent / name
            _refuse_irregular(path)
            if name.endswith(_ALLOWED_SUFFIX) or name == _ALLOWED_NAME:
                members.append(path.relative_to(source).as_posix())
    return sorted(members)


def _floor_guard(cli: Path) -> str:
    """Return `cli.py`'s `_require_python` source exactly as that file spells it."""
    source = cli.read_text(encoding="utf-8")
    for node in ast.parse(source).body:
        if isinstance(node, ast.FunctionDef) and node.name == "_require_python":
            segment = ast.get_source_segment(source, node)
            if segment:
                return segment
    raise ValueError(
        f"{cli} defines no recoverable `_require_python()`; the emitted __main__.py would ship "
        "no Python floor guard (C-1039)"
    )


def _date_time(source_date_epoch: str | None) -> tuple[int, int, int, int, int, int]:
    """Resolve the fixed `ZipInfo.date_time`: the argument, then the environment, then 1980."""
    raw = source_date_epoch if source_date_epoch is not None else os.environ.get("SOURCE_DATE_EPOCH")
    if raw is None:
        return DEFAULT_EPOCH
    moment = time.gmtime(int(raw))
    return (moment.tm_year, moment.tm_mon, moment.tm_mday, moment.tm_hour, moment.tm_min, moment.tm_sec)


def _add(
    archive: zipfile.ZipFile,
    name: str,
    payload: bytes,
    date_time: tuple[int, int, int, int, int, int],
) -> None:
    """Write one member with metadata that depends on nothing about this machine."""
    info = zipfile.ZipInfo(name, date_time=date_time)
    info.compress_type = zipfile.ZIP_STORED  # no compressor, so no zlib-version dependence
    info.create_system = 3  # Unix, so `external_attr` is read as a mode
    info.external_attr = 0o644 << 16
    archive.writestr(info, payload)


def build(source: Path, target: Path, *, source_date_epoch: str | None = None) -> str:
    """Pack `source` into a deterministic zipapp at `target`.

    Args:
        source: The `nox` package directory (`nox/src/nox`).
        target: Where to write the `.pyz`. Parent directories are created.
        source_date_epoch: `SOURCE_DATE_EPOCH` as a decimal string, or `None`
            to read the process environment and fall back to `DEFAULT_EPOCH`.

    Returns:
        The sha256 hex digest of the bytes written.

    Raises:
        ValueError: `source` is, or carries, a symlink or a non-regular file, or its
            `cli.py` defines no liftable `_require_python()`. Nothing is written.
    """
    members = _members(source)
    entry_point = MAIN_SOURCE.replace(_GUARD_MARKER, _floor_guard(source / "cli.py"))
    date_time = _date_time(source_date_epoch)

    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w") as archive:
        # Exactly one root member: the archive is `sys.path[0]` for the whole
        # process, so a second one would shadow a stdlib module by that name.
        _add(archive, "__main__.py", entry_point.encode("utf-8"), date_time)
        for member in members:
            # `O_NOFOLLOW` rather than a plain read: `_members` already refused every
            # symlink, but a check and a separate open are two syscalls with a window
            # between them, and a symlink swapped into it packs its target's bytes.
            with os.fdopen(os.open(source / member, os.O_RDONLY | os.O_NOFOLLOW), "rb") as handle:
                _add(archive, f"nox/{member}", handle.read(), date_time)

    payload = SHEBANG + buffer.getvalue()
    target.parent.mkdir(parents=True, exist_ok=True)
    target.unlink(missing_ok=True)  # never write (and chmod 0755) through a planted symlink
    target.write_bytes(payload)
    target.chmod(0o755)
    return hashlib.sha256(payload).hexdigest()


def main(argv: Sequence[str] | None = None) -> int:
    """Build the zipapp and print its sha256 digest, nothing else, to stdout.

    Args:
        argv: Command-line arguments; `None` reads `sys.argv[1:]`.

    Returns:
        A process exit code.
    """
    parser = argparse.ArgumentParser(prog="build_pyz", description="Build the deterministic nox.pyz zipapp.")
    parser.add_argument("source", type=Path, help="the nox package directory, i.e. nox/src/nox")
    parser.add_argument("target", type=Path, help="where to write the .pyz")
    arguments = parser.parse_args(argv)
    print(build(arguments.source, arguments.target))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
